# Use official Node.js image as base image
FROM node:18

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the package.json and package-lock.json (if available)
COPY package*.json ./

# Install the dependencies defined in package.json
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose port 9000 for the app
EXPOSE 9000

# Define the command to run the app
CMD ["node", "app.js"]
